<?php die; ?>
{
    "user_table": "#__ak_users",
    "dbdriver": "Mysqli",
    "dbhost": "localhost",
    "dbuser": "root",
    "dbpass": "5821222091",
    "dbname": "school",
    "prefix": "solo_",
    "timezone": "Europe\/Moscow",
    "live_site": "http:\/\/school\/administrator\/component\/akeeba\/",
    "session_timeout": "1440",
    "fs": {
        "driver": "file",
        "host": "127.0.0.1",
        "port": "21",
        "username": "",
        "password": "",
        "dir": "\/",
        "ssl": false,
        "passive": true,
        "directory": ""
    },
    "options": {
        "siteurl": "http:\/\/school\/administrator\/component\/akeeba\/",
        "confwiz_upgrade": 1,
        "show_howtorestoremodal": 0,
        "failure_timeout": "180",
        "failure_email_address": "",
        "failure_email_subject": "",
        "failure_email_body": "",
        "frontend_enable": true,
        "frontend_secret_word": "WhFrn9bh7lUm03whMkwCRXk0wA6qO7AO",
        "frontend_email_on_finish": true,
        "frontend_email_address": "",
        "frontend_email_subject": "",
        "frontend_email_body": "",
        "desktop_notifications": "0",
        "push_preference": "0",
        "push_apikey": "",
        "usesvnsource": false,
        "minstability": "stable"
    },
    "useencryption": "1",
    "dateformat": "",
    "stats_enabled": "1",
    "driver": "Mysqli",
    "host": "localhost",
    "user": "root",
    "pass": "5821222091",
    "name": "school",
    "mail": {
        "online": true,
        "mailer": "mail",
        "mailfrom": "",
        "fromname": "",
        "smtpauth": false,
        "smtpsecure": "0",
        "smtpport": "25",
        "smtpuser": "",
        "smtppass": "",
        "smtphost": "localhost"
    }
}